- src/ducks/apps/components/ApplicationRouting.jsx
- src/ducks/apps/index.js
- test/ducks/apps/components/__snapshots__/applicationRouting.spec.js.snap
Previously, we was adding `konnector-` before konnectors slug for the registry and remove it before installing in the cozy-stack.
Now we remove this specific behaviour.
> Remove specific konnector slug handling

- src/ducks/components/intents/IntentHandler.jsx
- src/targets/intents/index.jsx
An example which speaks by itself:
```jsx
<IntentHandler appData={appData} intents={cozy.client.intents}>
<InstallAppIntent action="INSTALL" type="io.cozy.apps" />
</IntentHandler>
```
> enhancement: Better IntentHandler, ready to use in any app

- src/ducks/apps/components/ApplicationPage/Details.jsx
- src/ducks/components/SmallAppItem.jsx
- test/components/__snapshots__/smallAppItem.spec.js.snap
- test/ducks/apps/components/applicationPage/__snapshots__/details.spec.js.snap
If the developer name was `Cozy` it was automatically replaced by `Cozy Cloud Inc`, this behaviour is now completely removed to just displayed the developer name provided by the application manifest.
> Remove Inc replacing for Cozy developer name

- src/styles/permissions.css
> Use grayscale for doctype icons

- src/ducks/apps/index.js
Avoid too much requests to fetch app versions, now the registry will return them with the apps listing.
__BREAKING CHANGE :__ This will only work with the latest version of the `cozy-apps-registry`.
> Let the registry handle last app versions infos

- manifest.webapp
- src/ducks/components/App.jsx
- src/ducks/components/intents/IntentRedirect.jsx
- test/__snapshots__/app.spec.js.snap
Pretty urgent for @drazik
This add an Intent redirection for apps with a slug, i.e. `/redirect?slug=trainline` will redirect to `/discover/trainline`. And update the manifest to handle this.
By default, redirection is still `/discover/<queryString>`
> Add Intent Redirect handling

- src/ducks/components/AppsLoading.jsx
- src/ducks/components/SmallAppItem.jsx
- src/locales/en.json
- src/styles/loading.css
- src/styles/sections.css
- src/styles/smallAppItem.css
- test/components/__snapshots__/smallAppItem.spec.js.snap
- test/components/smallAppItem.spec.js
- test/ducks/apps/components/__snapshots__/discover.spec.js.snap
- test/ducks/apps/components/__snapshots__/myApplications.spec.js.snap
Web
Mobile
Also fit the loading view with the new grid.
> Improve app items grid (+ loading)

- src/ducks/apps/components/ApplicationRouting.jsx
- test/ducks/apps/components/applicationRouting.spec.js
We now use `history.replace` in the ApplicationRouting component instead of `history.push` to handle modals state. It will replace the current history browser state instead of push a new one. We use that to avoid getting back to the uninstall modal (for example) by using the browser "previous button".
> Better handling modals routing with history.replace

- src/locales/en.json
Add translation for the new cc.cozycloud.autocategorization remote doctype used by banks
> feat: Add translation for cc.cozycloud.autocategorization

- src/ducks/apps/components/PermissionsModal.jsx
- src/ducks/apps/components/UninstallModal.jsx
- src/ducks/apps/index.js
- src/locales/en.json
- test/ducks/apps/components/__snapshots__/uninstallModal.spec.js.snap
* Remove animated header from uninstall modal
* Get back modal title in the permissions modal
* Typo on label reading
* Remove empty links in locales
> Minor modal UI fixes

- src/ducks/apps/index.js
Realtime in store is broken, as cozy-realtime is now intiialized with a config object and not cozy-client anymore.
So in this PR we got the domain and token from the top component, index.jsx.
This is not the best solution imho as the property is passed from component to subcomponents. We should better in the future use a global Cozy object for configuration, or maybe create a `<Cozy />` component which should pass all we need in the context.
> Due to cozy-realtime upgrade, the library does not use cozyclient as first parameter

- test/app.spec.js
- test/components/appVote.spec.js
- test/components/appsLoading.spec.js
- test/components/intents/intentRedirect.spec.js
- test/components/reactMarkdownWrapper.spec.js
- test/components/scrollToTop.spec.js
- test/components/sidebar.spec.js
- test/components/smallAppItem.spec.js
- test/ducks/apps/components/applicationPage/details.spec.js
- test/ducks/apps/components/applicationPage/gallery.spec.js
- test/ducks/apps/components/applicationPage/header.spec.js
- test/ducks/apps/components/applicationPage/index.spec.js
- test/ducks/apps/components/applicationPage/maintenance.spec.js
- test/ducks/apps/components/applicationRouting.spec.js
- test/ducks/apps/components/appsSection.spec.js
- test/ducks/apps/components/discover.spec.js
- test/ducks/apps/components/installModal.spec.js
- test/ducks/apps/components/myApplications.spec.js
- test/ducks/apps/components/permissionsList.spec.js
- test/ducks/apps/components/sections.spec.js
- test/ducks/apps/components/uninstallModal.spec.js
- test/ducks/apps/containers.spec.js
- test/jestLib/setup.js
Previously it was initialized in each files, now it's just in the Jest setup file
> Init Enzyme using jest setup files

- src/ducks/apps/components/ApplicationPage/Header.jsx
- src/ducks/apps/index.js
- src/ducks/components/AsyncButton.jsx
- test/ducks/apps/components/applicationPage/header.spec.js
Hotfix to use `home` slug instead of `collect`
> Use intent redirection to open konnector

- src/ducks/apps/index.js
Change an option in the fetch registry to get only the stable versions of apps
On trello : "(𝐒) [STO] Améliorer le chargement des apps"
> Change fetch registry option to get only stable versions

- src/ducks/components/intents/InstallAppIntent.jsx
- src/ducks/components/intents/IntentHandler.jsx
WIP: should me merge in ~the future `patch-1.2.5`, once~ `patch-1.2.4` ~will be stable~.
CREATE io.cozy.accounts after INSTALL io.cozy.apps
This PR add an interapp composition right after an interapp installation.
This composition is not performed if the first intent is called with a `configure: false` option.
> Intent composition

- src/styles/application.css
- Content page is scrollable again on Tablet
- Content page is well placed on Tablet.
Basically I extended the behaviour for mobile to tablet as well. That was it.
> fix: 🐛 Tablet layout

- src/ducks/apps/components/AppInstallation.jsx
- src/ducks/apps/components/ApplicationRouting/InstallRoute.jsx
- src/locales/en.json
On service update success, we won't redirect to the configure modal anymore.
> Better on update success

- manifest.webapp
- src/ducks/components/intents/IntentRedirect.jsx
The need here is to be able to open directly the `install` modal when we use the redirection.
~~I not very happy about the `action` variable naming here but I don't see a very good match here :/~~
We will use the `step` variable to specify `install`, `update`, `permissions` or `uninstall`
> Handle step on app page in intents

- src/ducks/apps/components/UninstallModal.jsx
- src/ducks/apps/index.js
- src/locales/en.json
- test/ducks/apps/components/__snapshots__/uninstallModal.spec.js.snap
- test/ducks/apps/components/uninstallModal.spec.js
When the user try to uninstall a web application that is linked to a mobile application, an error message is displayed. Before this PR, the error message was a JSON-API body that is not really clear for most users. Now, it is a localized message, with a link to the connected devices page.
> Improve error message when uninstalling a linked app

- src/ducks/apps/index.js
The store is currently slow to load the applications. It makes three requests:
- one for fetching apps from the registry
- one for fetching the installed web apps
- one for fetching the installed konnectors.
These 3 requests were sequential. I've tried to make the minimal changes to make them parallel. Maybe you will want to change more things to make the code clearer.
> fix: Optimize boot

- .travis.yml
Tag build was broken after https://github.com/cozy/cozy-store/commit/338551c15270ae30b2b10759f7de1f59533e60dc
Using the `only` directive prevent tags from being built.
See https://docs.travis-ci.com/user/customizing-the-build#safelisting-or-blocklisting-branches
(regexp test https://regex101.com/r/wsBW0t/1/)
> Travis: Fix branches directive 🚑

- package.json
- src/config/constants.json
- src/ducks/apps/components/AppInstallation.jsx
- src/ducks/apps/index.js
- src/ducks/components/App.jsx
- src/styles/install.css
- test/app.spec.js
- test/ducks/apps/__snapshots__/index.spec.js.snap
- test/ducks/apps/__snapshots__/reducers.spec.js.snap
- test/ducks/apps/_mockApps.js
- test/ducks/apps/_mockPKonnectorTrinlaneRegistryVersion.js
- test/ducks/apps/_mockPhotosRegistryVersion.js
- test/ducks/apps/_mockRegistryAppsResponse.js
- test/ducks/apps/components/__snapshots__/appInstallation.spec.js.snap
- test/ducks/apps/components/__snapshots__/appsSection.spec.js.snap
- test/ducks/apps/components/__snapshots__/discover.spec.js.snap
- test/ducks/apps/components/__snapshots__/myApplications.spec.js.snap
- test/ducks/apps/components/__snapshots__/sections.spec.js.snap
- test/ducks/apps/components/appInstallation.spec.js
- test/ducks/apps/components/applicationPage/__snapshots__/header.spec.js.snap
- test/ducks/apps/components/applicationRouting/__snapshots__/index.spec.js.snap
- test/ducks/apps/components/applicationRouting/__snapshots__/permissionsRoute.spec.js.snap
- test/lib/__snapshots__/getFilteredAppsFromSearch.spec.js.snap
- test/lib/__snapshots__/helpers.spec.js.snap
- yarn.lock
Allow to skip permissions when installing app or konnectors when the label is below a configurable `authorizedLabelLimit` number
> Add permissions skipping feature behing flag

- src/styles/smallAppItem.css
On systems with a dark theme, elements such as buttons or inputs have a
white text color. It was preventing the user from seeing the apps names
here, since `SmallAppItem`s are `button`s. By setting the color to
black, we avoid this issue.
| Before | After |
|--------|-------|
|![image](https://user-images.githubusercontent.com/1606068/55315853-828da480-546d-11e9-9cee-ad004196f722.png)|![image](https://user-images.githubusercontent.com/1606068/55315877-90432a00-546d-11e9-8698-480ef93bcd04.png)|
For information, my particular setup is Ubuntu 18.10 with dark theme enabled.
> fix(SmallAppItem): Set text color

- package.json
- src/targets/services/installSuggestion.js
- yarn.lock
Not used for now, but used in customization
> Add install suggestion service

- src/ducks/apps/components/ApplicationRouting/index.jsx
- test/ducks/apps/components/applicationRouting/__snapshots__/index.spec.js.snap
- test/ducks/apps/components/applicationRouting/index.spec.js
Allow to keep the URL queries when navigating within the app
> wip: Pass provided queries with path redirecting

- src/ducks/apps/components/AppInstallation.jsx
- src/locales/en.json
After an audit, BI asks us to update some of our wordings. Here, we introduce a new case for terms checkbox with partnership. With this, when an app has terms to accept and has a partnership, the terms checkbox label contains a little more informations. See below
Terms without partnership:
Terms with partnership:
> feat: Different translation for terms with partnership

- package.json
There is a problem with cozy-scripts' publish script that prevents us
from deploying the store to the registry. See
https://travis-ci.org/cozy/cozy-store/jobs/578391579#L570. This looks a
hard to debug issue. Using npx while we investigate this issue ensures
that the deployment is still working.
> chore: Fix cozyPublish script

- README.md
Actually link to the *Prerequisites* section so the reader can see both of them.
> docs: Fix link to *Install the development env.*

- src/ducks/apps/components/Sections/components/SmallAppItem.jsx
- src/ducks/apps/components/Sections/components/__snapshots__/SmallAppItem.spec.jsx.snap
So one can read long family names & budget insight connectors developer.
> feat: Show full app developer on hover

- src/ducks/apps/components/InstallModal.jsx
- test/ducks/apps/components/__snapshots__/installModal.spec.js.snap
- test/ducks/apps/components/installModal.spec.js
Since our latest UI upgrade, we had to move the `FocusTrap` component inside the Modal https://github.com/cozy/cozy-store/commit/60fdca5c4332658516cf58b7622c5b68bc14bb0a#diff-44b7cb5dee073537051fb3dbc0e76da8
Because of that, in the DOM we had something like : 
```
<div class="modal">
<div>
<div class="modalheader"/>
...
</div>
</div>
```
The result was : if the content of the Modal was too long, it was displayed outside of the modal. 
We decided to remove the FocusTrap on the Modal for two things: 
- It's not part of our current QA before deploying but we can still navigate by tabbing 
- It should be done by Cozy-UI itself and not by the app
> fix: Remove FocusTrap on AppInstall

- src/ducks/apps/client-helpers.js
This is due to a hardcoded limit of 200 in the request getting the list
of apps and connectors.
I set it to 300 for the weekend, but the better fix would be to add
registry to cozy-client and with a proper pagination handling.
> fix: Some hidden connectors in store

- src/targets/intents/index.jsx
Since we pass `store` to cozyProvider, we need to set `store:false` when creating a new cozy-client
> fix: Don't force store creation

- src/styles/application.css
We previously added this overflow hidden
when we added the CozyTheme wrapper. I
don't know why. This overflow worked locally
but not on production since the cozy bar's
style was the one used.
Let's !important to fix the issue quickly
> fix: Double Scroll on some browsers

- src/ducks/apps/components/PermissionsList.jsx
- src/locales/en.json
- src/locales/fr.json
- test/ducks/apps/components/__snapshots__/permissionsList.spec.js.snap
Permission modal was not clear enough about what was shared or not
We think that the new wording will fix this problem
> feat: Reword permissions modal

- src/locales/en.json
- src/locales/fr.json
- test/components/__snapshots__/sidebar.spec.js.snap
- test/ducks/apps/components/__snapshots__/myApplications.spec.js.snap
Previous wording was confusing and user may not understand that this
menu was about `installed` applications
`Installed application` was proposed as an alternative but this title
was too long to fit in the navbar, so we chose to use `Installed`
instead
> feat: Reword `My applications` to `Installed`

- src/ducks/apps/components/ApplicationPage/Header.jsx
The `openwith` icon is used as an indication that the link will leave
the cozy domain. Here we are removing this icon to avoir confusion as
the `open` button stay inside of the cozy and inside of the same tab
> feat: remove `open` button's icon

- package.json
- src/ducks/components/Root.jsx
- yarn.lock
⚠️ this PR is a draft as it should be completed by bumping `cozy-ui` version after related PR is merged
When the main content (application list) is scrollable but its content is not large enough (i.e. a few apps in each list section), then the scroll bar is stick to the apps list instead of being stick to the browser right side
This fix make the main content always take all remaining space
`u-flex-grow-1` has been added to `<CozyTheme>` as this is the first child directly under the main application container (which is set to be a flexbox)
Also the scrollable area highly depends on navbar size, this has been fixed in cozy-ui with https://github.com/cozy/cozy-ui/pull/1881
> fix: Make the main content fill the remain space of the browser view

- src/styles/permissions.css
In Permissionlist categories, icon size was affected by the category
text's length
Now the text block doesn't grow and so icon cannot be shrink and always
has the desired size
> fix: fix permission list category to have fixed icon size

- src/ducks/components/intents/InstallAppIntent.jsx
- test/components/intents/installAppIntent.spec.js
Previous commit that refactored CozyData usage forgot some refactoring in `installAppIntent`
Related commit: 5d3659bfba0680e6413ad256411be1f27a32be45
> fix: Use correct CozyData membres in intent

- src/targets/intents/index.jsx
Previous commit that refactored CozyData usage forgot some refactoring
in `intents/index.jsx`
Related commit: 5d3659bfba0680e6413ad256411be1f27a32be45
and f5c6deb970ca5db3866164555a0837726583ba0d
> fix: Fix parsing of CozyData in intent

- CHANGELOG.md
- package.json
- yarn.lock
This version contains new styles for `AppTiles` regarding if the app is
installed, has an update or has a title that can fit in two lines
Related PR : cozy/cozy-ui#1884 and cozy/cozy-ui#1885
> feat: Bump cozy-ui to 51.9.0

- package.json
To have next dev version visible
For now installing registry://store/dev channel gives us the same version as the stable channel
> chore: Bump version to 1.9.11

- src/config/permissionsIcons.json
- src/config/remote-doctypes.json
- src/locales/en.json
- src/locales/fr.json
This will be used for apps sending measures to the .eu DACC
> feat: Add locales and icon for eu.mycozy.dacc remote doctype

- src/ducks/apps/components/ApplicationPage/Header.jsx
- src/ducks/apps/components/ApplicationPage/index.jsx
- src/ducks/apps/components/ApplicationRouting/InstallRoute.jsx
- src/ducks/apps/components/ApplicationRouting/index.jsx
- src/ducks/apps/components/Discover.jsx
- test/ducks/apps/components/applicationPage/header.spec.js
Old `konnectorOpenUri` mechanisme is removed in favor of cozy-intent
based one
Those mechanisms are used to tell parent react-native app that a
connector pane needs to be opened
`konnectorOpenUri` required the parent react-native app to inject a
token in the store's url so the store would know if executed in a
react-native context or not, and then intercept navigation URLs to
detect if a connector needs to be opened. This implementation was not
easy to understand
New implementation uses cozy-device-helper to detect if run from
CozyFlagship app and the uses cozy-intent messaging service to ask for
displaying a connector
---
TODO:
> feat: use cozy-intent instead of konnectorOpenUri

- src/config/permissionsIcons.json
- src/locales/en.json
- src/locales/fr.json
Since `cc.cozycloud.sentry` is deprecated, we are migrating to `cc.cozycloud.errors`. So let's add this permission
> feat: Add cc.cozycloud.errors permission

- CHANGELOG.md
- package.json
- yarn.lock
This version retrieves a feature that allow `cozy-client` to force
HTTPs on fetches if `window.cozy.isSecureProtocol` is `true` (which
should be the case when `cozy-home` is served from ReactNative)
Related PR: cozy/cozy-client#1172
> feat: Upgrade cozy-client to 30.0.0

- src/ducks/apps/components/Sections/index.spec.jsx
- src/locales/en.json
At the moment, the SNCF konnector is in maintenance. So we need to display another konnector in the placeholder.
I updated only the source language (EN), and updated the 2 others (FR, DE) on Transifex. Is it the good way to do ?
> fix: Update search text placeholder

- package.json
- src/ducks/apps/components/QuerystringSections.jsx
- src/ducks/apps/components/Sections/components/Filters.jsx
- yarn.lock
```
* Hide app under maintenance by default
```
This PR is a fix for the feature to have an filter to show app under maintenance. I didn't apply a filter by default to hide app under maintenance without showing into query url params.
**Related PRs:**
- https://github.com/cozy/cozy-ui/pull/2312
> fix: Hide app under maintenance by default

- src/ducks/apps/components/QuerystringSections.jsx
```
* Filter taken back into account
```
QuerystringSections render on every action on cozy-store to avoid that we put a memo on it. This creates an issue on filter update to get back to normal we remove Memo.
> fix: filter take into account back

- src/ducks/apps/components/Discover.jsx
- src/ducks/components/AppVote.jsx
- test/components/__snapshots__/appVote.spec.js.snap
- test/ducks/apps/components/__snapshots__/discover.spec.js.snap
Feedback CTA was disabled waiting a new feedback tool.
[Edit] @Crash-- [https://feedback.cozy.io](https://feedback.cozy.io) is now correctly working. Do I still need to add a flag ? 
```
* Add feedback link in store
```
> feat: Add feedback CTA

- src/ducks/components/AppRouter.jsx
- test/components/__snapshots__/sidebar.spec.js.snap
- yarn.lock
```
* make discover the default route
```
After the refacto of react-router-v6, the default route was myapps. This fix make by default the discove as before the refacto.
> fix(AppRouter.jsx): make discover the default route

- src/ducks/apps/components/UninstallModal.jsx
- test/ducks/apps/components/__snapshots__/uninstallModal.spec.js.snap
Happened on some mobile screens like 360*568. Solved by updating to new Buttons from cozy-ui.
```
* Trash icon size was too small on uninstall button on some mobile
```
> fix: Trash icon size was too small on uninstall button on some mobile screens

- src/ducks/apps/components/PermissionsList.jsx
- src/locales/en.json
- src/locales/fr.json
- test/ducks/apps/_mockWebappRegistryVersion.js
- test/ducks/apps/components/__snapshots__/permissionsList.spec.js.snap
- test/ducks/apps/components/permissionsList.spec.js
```
* The text on the consent page must be dynamic, if the user installs a "webapp" or a "konnector"
```
> fix: Consent page wording

- package.json
- src/ducks/apps/components/ApplicationPage/Header.jsx
- src/ducks/apps/components/ApplicationRouting/InstallRoute.jsx
- src/ducks/apps/components/Discover.jsx
- src/ducks/apps/index.js
- src/ducks/components/AppRouter.jsx
- test/ducks/apps/components/applicationPage/header.spec.js
- test/ducks/apps/components/applicationRouting/installRoute.spec.js
- test/ducks/apps/components/discover.spec.js
- yarn.lock
Le besoin actuel est que depuis MesPapiers on souhaite installer un connecteur, 
et revenir dans l'application après installation du connecteur. Pour se faire 
on compute depuis l'app la route à retourner, et on la passe à Store depuis 
l'url et le search param `redirectAfterInstall`.
```
* Add `redirectAfterInstall` search param support
* Keep search params when (un)installing an app/connector
* Upgrade cozy-ui from 79.0.0 to 79.3.0
* Extract openApp func from Header
```
> Add `redirectAfterInstall` search params to be able to redirect after  installing an app/connector

- src/ducks/apps/components/QuerystringSections.jsx
Using the wrong parent variable as ti was window.parent instead of component props
```
* My apps page show all apps by default
```
> fix: My apps show maintenance apps by default

- src/ducks/apps/components/PermissionsList.jsx
- test/ducks/apps/components/__snapshots__/permissionsList.spec.js.snap
```
* The order of permissions could change between pre-installation and post-installation.
More precisely, the `io.cozy.certified.carbon_copy` permission which was returned by the stack at a different position.
To fix this, we sort the permissions (by the current Cozy language)
```
> fix: Sorted permissions list

- src/ducks/apps/components/Sections/index.spec.jsx
- src/locales/de.json
- src/locales/en.json
- src/locales/fr.json
Ameli -> CAF because health konnectors are deactivated on some contexts.
```
* Update search wording
```
> feat: Update search wording

- manifest.webapp
- src/ducks/components/App.jsx
- src/ducks/components/PushBanners/BannerForAA.jsx
- src/ducks/components/PushBanners/BannerForFlagshipApp.jsx
- src/ducks/components/PushBanners/BannerForPass.jsx
- src/ducks/components/PushBanners/PushBanners.jsx
- src/ducks/components/PushBanners/helpers.js
- src/ducks/components/PushBanners/helpers.spec.js
- src/ducks/components/PushBanners/index.jsx
- src/ducks/queries.js
- src/locales/de.json
- src/locales/en.json
- src/locales/fr.json
- src/locales/nl_NL.json
- src/locales/pl.json
- test/__snapshots__/app.spec.js.snap
Selon une certaine logique, nous ajoutons 2 bannière push pour proposer l'app amirale et cozy pass mobile.
Après merge de cette PR, il faudra mettre à jour la doc de cozy concernant `io.settings.display` et le nouveau flag.
```
* Add AA and Pass mobile push banners
```
> Add AA and Pass mobile push banners

- src/ducks/components/PushBanners/BannerForFlagshipApp.jsx
- src/ducks/components/PushBanners/helpers.js
- src/ducks/components/PushBanners/helpers.spec.js
- src/locales/fr.json
Le software_id n'est pas utilisé côté stack, c'est ici que ça se passe https://github.com/cozy/cozy-stack/blob/master/model/bitwarden/oauth.go#L54-L87
Dans la solution retenue, on discrimine volontairement tous les clients mobile bitwarden, on se base donc sur `github.com/bitwarden/mobile`
> fix(PushBanners): Pass mobile wasn't detected correctly

- src/ducks/apps/components/ApplicationPage/Details.jsx
- src/ducks/apps/components/ApplicationPage/index.jsx
- src/ducks/apps/components/ApplicationRouting/PermissionsRoute.jsx
- src/ducks/apps/components/Discover.jsx
- src/ducks/apps/components/MyApplications.jsx
- src/ducks/apps/components/PermissionsModal.jsx
- src/ducks/apps/components/Sections/Sections.jsx
- src/ducks/apps/components/SidebarCategories.jsx
- src/styles/sidebar.css
- test/ducks/apps/components/applicationPage/__snapshots__/details.spec.js.snap
- test/ducks/apps/components/applicationPage/__snapshots__/index.spec.js.snap
- test/ducks/apps/components/applicationPage/details.spec.js
- test/ducks/apps/components/applicationPage/index.spec.js
- test/ducks/apps/components/applicationRouting/__snapshots__/permissionsRoute.spec.js.snap
- test/ducks/apps/components/applicationRouting/channelRoute.spec.js
- test/ducks/apps/components/applicationRouting/permissionsRoute.spec.js
- test/ducks/apps/components/applicationRouting/uninstallRoute.spec.js
- test/ducks/apps/components/discover.spec.js
- test/ducks/apps/components/myApplications.spec.js
When navigating from Sections page into Application page we lose the current selected category
This impact is that when we close the Application page using the `BACK TO THE LIST` button, then we cannot display the previously selected section and instead we display the full apps list
Another bug is that the previous search filter and the hide/show apps in maintenance filter are lost
This PR fixes this issue those bugs but also do some refactorings, and fix the Sidebar CSS so menu won't overflow anymore from the sidebar
When displaying the section page (top), the left menu overflows
The `type=konnector&category=insurance` is lost when navigating to the application page (bottom)
The Sidebar selection is lost when navigating to the application page (bottom)
When displaying the section page …
> fix: Keep selected section and filters when navigating between Sections page and Application pages

- src/ducks/apps/components/ApplicationPage/index.jsx
- src/ducks/apps/components/Discover.jsx
- src/ducks/apps/components/MyApplications.jsx
- src/ducks/apps/components/Sections/components/Filters.jsx
In a few scenarios, we don't inject the cozy.bar object to the react tree. This is the case for the Intent use case. Since we don't display the cozy-bar, we don't inject it in order to have a smaller bundle.
And within the code, if a component need the cozy.bar to be displayed and if it's called within an intent, then we polyfil the global var.
But since the destructuring object was done at the build / import phase and not during the component lifecycle, we got an error telling that we can't reader BarRight from undefined, even if the component was not displayed.
So to fix that, we should only call cozy.bar within the component lifecycle.
> fix: Don't call cozy.bar outside of the React Tree

- manifest.webapp
- package.json
- src/ducks/apps/components/ApplicationPage/Header.jsx
- src/ducks/apps/components/ApplicationPage/helpers.js
- src/ducks/apps/components/ApplicationPage/helpers.spec.js
- src/ducks/apps/components/ApplicationPage/index.jsx
- src/ducks/apps/components/Sections/Sections.jsx
- src/ducks/apps/components/Sections/index.spec.jsx
- src/ducks/search/components.jsx
- yarn.lock
Added an option to terminate the Intent when you want to "Open" an installed but not connected connector. Necessary because an app like Mespapiers needs to be able to connect a connector already installed.
`disableClick` is no longer useful, because we want to access the details of an already installed connector.
```
* Via the Intent, we can access an installed connector page.
The action of clicking on the "Open" button can close the Intent via the `data={{ terminateIfInstalled: true }}` option of the IntentIframe.
```
> feat(Intent): Add `terminateIfInstalled` option to intentData

- manifest.webapp
- src/ducks/apps/components/QuerystringSections.jsx
- src/ducks/components/intents/InstallAppIntent.jsx
- src/ducks/components/intents/helpers.js
- src/ducks/components/intents/helpers.spec.js
- test/components/intents/InstallAppIntentContent.spec.js
Just like `category` or in addition, `qualificationLabels` allows you to filter the list of Store applications based on their qualification label.
```
* Add filter by qualification label for INSTALL intent
```
> feat: Add filter by qualification label for INSTALL intent

- src/targets/browser/index.ejs
- src/targets/intents/index.ejs
Our custom theme CSS was not taken into account because cozy-ui CSS was inserted after.
```
* Custom theme colors were not taken into account
```
>  fix: Move custom theme CSS at end of <head>

- package.json
- src/ducks/AlternativeStore/tests/transformData.spec.ts
- src/ducks/AlternativeStore/transformData.ts
- src/ducks/AlternativeStore/types/index.ts
- src/ducks/apps/components/ApplicationPage/Details.jsx
- src/ducks/apps/components/ApplicationPage/index.jsx
- src/locales/en.json
- src/locales/fr.json
- yarn.lock
```
* Update cozy-client from 48.13.1 to 48.25.0
```
**Related PRs:**
- https://github.com/cozy/cozy-ui/pull/2697
- https://github.com/konnectors/toutatice/pull/482
> [VO-1037 & VO-1072] fix: Some fixes on additional apps 

- src/config/apps.json
We introduced a "fake" app, the dataproxy, that is meant to be a core component to handle data and notably to persist it locally, but should not be displayed.
```
* Hide dataproxy app
*
*
```
> [PRD-538] feat: Hide dataproxy app

- package.json
- yarn.lock
Benefit from the new apps.hidden flag, to hide apps in the bar menu. This is typically done to hide the new dataproxy app used for search.
```
* Upgrade cozy-bar to hide apps from flag
*
*
```
> [PRD-538] feat: Upgrade cozy-bar for new flag

- package.json
- yarn.lock
cozy-dataproxy-lib >= 4.2.0 is not working with flagship app. We need to find a fix but as we want to release apps now, lets downgrade.
> fix: Downgrade cozy-dataproxy-lib
