cozy/cozy-store

- src/ducks/apps/components/Discover.jsx
- src/ducks/apps/index.js
* Handle app icon from registry
* Fix bug about missing spinner in install button
> Improvements

- manifest.webapp
- src/ducks/apps/components/AppInstallation.jsx
- src/ducks/apps/components/InstallModal.jsx
- src/ducks/apps/index.js
- src/ducks/components/intents/InstallAppIntent.jsx
- src/ducks/components/intents/IntentHandler.jsx
- src/locales/en.json
- src/styles/index.styl
- src/styles/install.css
- src/styles/intents.css
- src/styles/modal.css
- src/targets/intents/index.ejs
- src/targets/intents/index.jsx
- test/ducks/apps/components/__snapshots__/applicationRouting.spec.js.snap
- test/ducks/apps/components/__snapshots__/installModal.spec.js.snap
- test/ducks/apps/components/installModal.spec.js
This PR :
* adds intent handling
* extract the `<AppInstallation />` component from `<InstallModal />` to use it in `<KonnectorInstallIntent />`
> feat: add intent for konnector installation ✨

- src/ducks/components/intents/IntentHandler.jsx
How did we make this work last week ?
> Fix undefined attributes in intent handler

- src/ducks/apps/Containers.jsx
- src/ducks/apps/components/AppInstallation.jsx
- src/ducks/apps/components/ApplicationPage/Details.jsx
- src/ducks/apps/components/ApplicationRouting.jsx
- src/ducks/apps/components/InstallModal.jsx
- src/ducks/apps/components/MyApplications.jsx
- src/ducks/apps/index.js
- src/lib/getChannelFromSource.js
- src/styles/install.css
- test/ducks/apps/components/__snapshots__/installModal.spec.js.snap
- test/ducks/apps/components/myApplications.spec.js
Fetch registry also in installed apps view and fix issue about canceling channel switching
> Better handling channel switching

- src/config/constants.json
- src/ducks/apps/index.js
Replace the providers view by the connector accounts picker
> Change collect related link

- src/locales/en.json
- test/ducks/apps/components/applicationPage/__snapshots__/header.spec.js.snap
> Fix wording for install button

- package.json
- src/ducks/apps/components/AppInstallation.jsx
- src/ducks/apps/components/ApplicationRouting.jsx
- src/ducks/apps/components/Discover.jsx
- src/ducks/apps/components/InstallModal.jsx
- src/ducks/apps/components/MyApplications.jsx
- src/ducks/apps/components/UninstallModal.jsx
- src/ducks/apps/index.js
- src/ducks/components/App.jsx
- src/ducks/components/intents/InstallAppIntent.jsx
- test/app.spec.js
- test/ducks/apps/components/__snapshots__/installModal.spec.js.snap
- test/ducks/apps/components/__snapshots__/uninstallModal.spec.js.snap
- test/ducks/apps/components/installModal.spec.js
- yarn.lock
Use the brand new [`cozy-realtime`](https://github.com/cozy/cozy-realtime) to handle realtime with the stack.
> Optimisations + handle realtime when app installing

- src/ducks/apps/components/AppsLoading.jsx
- src/ducks/apps/components/Discover.jsx
- src/styles/index.styl
- src/styles/loading.css
- test/ducks/apps/components/__snapshots__/discover.spec.js.snap
> Improve app loading view

- src/ducks/apps/Containers.jsx
- src/ducks/apps/components/ApplicationPage/Header.jsx
- src/ducks/apps/components/ApplicationPage/index.jsx
- src/ducks/apps/components/AppsSection.jsx
- src/ducks/apps/components/Discover.jsx
- src/ducks/apps/components/MyApplications.jsx
- src/ducks/apps/index.js
- src/ducks/components/App.jsx
- src/ducks/components/AppsLoading.jsx
- src/ducks/components/SmallAppItem.jsx
- test/ducks/apps/__snapshots__/containers.spec.js.snap
- test/ducks/apps/components/__snapshots__/myApplications.spec.js.snap
- yarn.lock
Icons fetching is now out from the app initial fetching and a placeholder is displayed while the icone is being fetching after.
> Load icons after first apps fetching

- src/styles/loading.css
> Darker loading color

- src/ducks/apps/components/ApplicationPage/Header.jsx
- src/ducks/apps/components/ApplicationPage/index.jsx
- src/ducks/apps/components/ApplicationRouting.jsx
- src/ducks/apps/components/UninstallModal.jsx
- src/locales/en.json
- test/ducks/apps/components/__snapshots__/applicationRouting.spec.js.snap
- test/ducks/apps/components/__snapshots__/uninstallModal.spec.js.snap
- test/ducks/apps/components/applicationRouting.spec.js
- test/ducks/apps/components/uninstallModal.spec.js
Disable the button in the application page instead in the uninstall modal.
> Disable uninstall button if app not uninstallable

- src/ducks/apps/Containers.jsx
- src/ducks/apps/components/ApplicationRouting.jsx
- src/ducks/apps/components/Discover.jsx
- src/ducks/apps/components/InstallModal.jsx
- src/ducks/apps/components/UninstallModal.jsx
- src/ducks/apps/index.js
- test/ducks/apps/components/uninstallModal.spec.js
Fix the issue about installing using Dev/Beta channel + handle app update and uninstall with realtime.
> Minor fixes included for Dev/Beta version issue

- src/ducks/apps/components/DropdownFilter.jsx
- src/ducks/apps/components/Sections.jsx
- test/ducks/apps/components/__snapshots__/sections.spec.js.snap
> Remove fixed options from filter dropdown

- src/ducks/apps/components/ApplicationRouting.jsx
- src/locales/en.json
- test/ducks/apps/components/__snapshots__/discover.spec.js.snap
- test/ducks/apps/components/__snapshots__/myApplications.spec.js.snap
Alerter was broken due to cozy-ui update. This PR also add a fix to avoid reacting (page change) on install/uninstall error
> Fix alerter messages for install/Uninstall

- src/ducks/apps/components/ApplicationRouting.jsx
- test/ducks/apps/components/__snapshots__/applicationRouting.spec.js.snap
> Fix mobileFullscreen prop for IntentModal

- src/ducks/apps/index.js
Remove just potential `/` before the name.
> Better handling app screenshots

- src/ducks/apps/components/AppInstallation.jsx
- src/styles/install.css
Improve space usage in the modal.
> Better install modal UI

- src/ducks/apps/Containers.jsx
- src/ducks/apps/components/Sections.jsx
- src/ducks/apps/components/SidebarCategories.jsx
- src/ducks/components/Sidebar.jsx
- src/lib/helpers.js
- src/styles/dropdownFilter.css
- src/styles/index.css
- src/styles/sidebar.css
- test/components/__snapshots__/sidebar.spec.js.snap
- test/ducks/apps/components/__snapshots__/sections.spec.js.snap
> Better categories handling

- src/ducks/apps/components/SidebarCategories.jsx
- src/lib/helpers.js
> Improve categories side menu

- src/ducks/apps/index.js
- src/ducks/components/intents/InstallAppIntent.jsx
Realtime was disable on intents and breaking installation feedback.
> 🚑 Get back realtime on intents

- src/ducks/apps/components/Discover.jsx
- src/ducks/apps/components/MyApplications.jsx
- src/ducks/components/App.jsx
- src/targets/browser/index.ejs
- test/__snapshots__/app.spec.js.snap
- test/ducks/apps/components/__snapshots__/discover.spec.js.snap
- test/ducks/apps/components/__snapshots__/myApplications.spec.js.snap
Used `<Layout />` UI Component & added iPhoneX support along.
~~⚠️ Waiting for a new release of UI.~~
> refactor: Use Layout UI component

- src/ducks/apps/components/ApplicationPage/index.jsx
- src/locales/en.json
- src/styles/application.css
- test/ducks/apps/components/applicationPage/__snapshots__/index.spec.js.snap
> Add back button on application page

- src/ducks/apps/components/DropdownFilter.jsx
- src/ducks/apps/components/SidebarCategories.jsx
- src/lib/helpers.js
- src/locales/en.json
- test/components/__snapshots__/sidebar.spec.js.snap
- test/ducks/apps/components/__snapshots__/discover.spec.js.snap
> Improve categories handling

- src/ducks/apps/components/AppsSection.jsx
- src/ducks/apps/components/DropdownFilter.jsx
- src/ducks/apps/components/Sections.jsx
- src/ducks/apps/components/SidebarCategories.jsx
- src/ducks/components/SmallAppItem.jsx
- src/lib/helpers.js
- src/styles/sections.css
- test/ducks/apps/components/__snapshots__/appsSection.spec.js.snap
- test/ducks/apps/components/__snapshots__/sections.spec.js.snap
- test/ducks/apps/components/appsSection.spec.js
Also:
* Fix placeholder on mobile view
* Improve apps sections titles
> Better categories splitting between webapp/konnectors

- src/ducks/components/SmallAppItem.jsx
- src/locales/en.json
- src/styles/appVote.css
- src/styles/smallAppItem.css
- test/components/__snapshots__/smallAppItem.spec.js.snap
Add the `By` before the developer name, and fix some minor margins.
> Minor app items improvements

- src/locales/en.json
Add the english translation of the `io.cozy.bank.balancehistories` doctype.
> feat: Add io.cozy.bank.balancehistories translation

- src/ducks/apps/components/ApplicationRouting.jsx
- test/ducks/apps/components/__snapshots__/applicationRouting.spec.js.snap
Use 35rem for the Collect interapp modal
> Better height for collect interapp modal

- src/ducks/components/intents/InstallAppIntent.jsx
Wrong usage of installApp in interapp.
> Fix issue installing using interapp

- src/ducks/apps/components/Discover.jsx
- src/ducks/apps/components/MyApplications.jsx
- src/ducks/components/Root.jsx
- src/ducks/components/ScrollToTop.jsx
- test/ducks/apps/components/__snapshots__/discover.spec.js.snap
- test/ducks/apps/components/__snapshots__/myApplications.spec.js.snap
Fix scroll to top to automatically scroll to the top of the window when navigating through the application.
> Fix broken scroll to top behavior

- src/ducks/apps/components/ApplicationPage/Details.jsx
- src/ducks/apps/components/ApplicationPage/Maintenance.jsx
- src/ducks/apps/components/ApplicationPage/index.jsx
- src/locales/en.json
- test/ducks/apps/components/applicationPage/__snapshots__/index.spec.js.snap
> Revert maintenance subtitle wording

- src/ducks/apps/components/SidebarCategories.jsx
- src/lib/helpers.js
- test/components/__snapshots__/sidebar.spec.js.snap
- test/lib/__snapshots__/helpers.spec.js.snap
- test/lib/helpers.spec.js
Those were breaking the HMR each time the app is rendered again.
> Fix HMR preventing issues

- src/ducks/apps/components/TransparencyModal.jsx
- test/ducks/apps/components/__snapshots__/transparencyLabel.spec.js.snap
- test/ducks/apps/components/__snapshots__/transparencyNotice.spec.js.snap
- test/ducks/apps/components/transparencyLabel.spec.js
- test/ducks/apps/components/transparencyNotice.spec.js
> Add tests for transparency components

- src/ducks/apps/components/DropdownFilter.jsx
- src/styles/dropdownFilter.css
- src/styles/sections.css
> Add fixed categories dropdown for mobile usage

- src/styles/sections.css
- src/styles/smallAppItem.css
> Improve mobile app tiles styles

- src/ducks/apps/index.js
A part of initialization was missing in #339, don't ask me why.
> Fix realtime initialization

- src/ducks/apps/components/AppInstallation.jsx
- src/lib/getChannelFromSource.js
- test/lib/getChannelFromSource.spec.js
* Fix channel install not working
* Fix channel detection to display in the app page
> Fix bug on app channel update

- src/targets/browser/index.ejs
- src/targets/intents/index.ejs
Add the app slug as a variable provided by the stack (necessary for the cozy-bar)
> Handle app slug from the stack

- src/ducks/apps/Containers.jsx
- src/ducks/apps/components/AppInstallation.jsx
- src/ducks/apps/components/ApplicationRouting/InstallRoute.jsx
- src/ducks/apps/components/ApplicationRouting/index.jsx
- test/ducks/apps/components/applicationRouting/__snapshots__/index.spec.js.snap
Wrong method was used and passed.
> Fix manual update issue

- src/ducks/apps/components/ApplicationPage/Header.jsx
- src/ducks/components/ScrollToTop.jsx
- src/styles/dropdownFilter.css
- src/styles/sections.css
- src/styles/smallAppItem.css
- src/styles/viewTitle.css
- test/components/scrollToTop.spec.js
- test/ducks/apps/components/__snapshots__/discover.spec.js.snap
- test/ducks/apps/components/__snapshots__/myApplications.spec.js.snap
- test/ducks/apps/components/applicationPage/__snapshots__/header.spec.js.snap
* Less transform for tiles on hover on smaller views
* Fix scroll to top for mobile
* Smaller view title on mobile
* Use secondary theme for uninstall button
* Better sections titles/subtitles
* Remove shadow on mobile dropdown + fix dropdown height
> Global fixes

- src/styles/application.css
Add this style to fix a wrong bar styles overwriting
> Temp fix for back button style

- src/ducks/apps/components/AppInstallation.jsx
Was missing from the app installation component
> Alert on install success

- src/config/apps.json
Hide collect since it will be replaced by the Home
> Hide collect from store apps

- renovate.json
[This config](https://github.com/cozy/cozy-libs/blob/master/packages/renovate-config-cozy-app/package.json)
> Use renovate config cozy-app

- src/styles/application.css
> Align back button to left

- src/styles/appVote.css
> App vote padding

- src/ducks/apps/Containers.jsx
- src/ducks/apps/components/AppInstallation.jsx
- src/ducks/apps/components/ApplicationRouting/InstallRoute.jsx
- src/ducks/apps/components/ApplicationRouting/index.jsx
- src/ducks/apps/components/Discover.jsx
- src/ducks/apps/components/MyApplications.jsx
- src/ducks/apps/index.js
- test/ducks/apps/__snapshots__/containers.spec.js.snap
- test/ducks/apps/components/applicationRouting/__snapshots__/index.spec.js.snap
The update was not triggered correctly
> Fix manual update

- package.json
- src/ducks/apps/components/AppInstallation.jsx
- src/ducks/components/intents/InstallAppIntent.jsx
- yarn.lock
Due to recent changes, intents were broken.
> Fix intents

- src/ducks/components/AsyncButton.jsx
Error was due to props passed to AsyncButton component and then Button component
> Remove React warning

- package.json
- src/ducks/apps/components/ConfigureModal.jsx
- yarn.lock
Update cozy-ui to get scroll locking + only use height for non mobile view.
> Get back scroll behaviour on configure modal

- src/ducks/apps/components/AppInstallation.jsx
- src/ducks/apps/components/ApplicationPage/index.jsx
- src/ducks/apps/components/ApplicationRouting/AppRoute.jsx
- test/ducks/apps/components/applicationPage/__snapshots__/index.spec.js.snap
- test/ducks/apps/components/applicationRouting/__snapshots__/appRoute.spec.js.snap
- Add FocusTrap on App installation Modal
- Handle FocusTrap inception
> fix: 🐛 Modal works well with FocusTrap

- src/styles/application.css
To limit the modal element size on huge screen.
> limit the width size of an app modal

- src/ducks/apps/components/ApplicationPage/index.jsx
- src/ducks/apps/components/ApplicationRouting/AppRoute.jsx
- src/ducks/apps/components/ApplicationRouting/index.jsx
- test/ducks/apps/components/applicationPage/index.spec.js
- test/ducks/apps/components/applicationRouting/__snapshots__/index.spec.js.snap
Now we have to listen the page instead of window since it uses an absolute position
> Get back animated bar icon on app page mobile

- package.json
- src/ducks/apps/components/AppInstallation.jsx
- src/ducks/apps/components/ChannelModal.jsx
- src/ducks/apps/components/InstallModal.jsx
- src/ducks/components/App.jsx
- src/styles/application.css
- src/styles/dropdownFilter.css
- src/styles/install.css
- test/__snapshots__/app.spec.js.snap
- test/ducks/apps/components/__snapshots__/installModal.spec.js.snap
- yarn.lock
- Update UI
- Reforged Modal
- Better Z-Index management
> fix: 🐛 Better app install Modal's layout

- src/styles/intents.css
> fix: 🐛 App installation intent broken layout

- src/ducks/apps/components/AppInstallation.jsx
- src/styles/install.css
- src/styles/intents.css
Extend previous fix for IntentModal to every modal.
> fix: 🐛 Modal controls position

- src/ducks/apps/components/ApplicationPage/index.jsx
- test/ducks/apps/components/applicationPage/__snapshots__/index.spec.js.snap
Fix icon in bar when scrolling on app page on mobile
> fix: :bug: Use AppIcon for mobile animated header

- src/ducks/apps/index.js
Some args were removed without changing the calls
> Function args changed but not the calls

- src/ducks/components/intents/IntentHandler.jsx
- src/styles/intents.css
Spinner was positionned top right
> Fix spinner position on in IntentHandler

- src/ducks/apps/index.js
Get the installed status when fetched app sooner
> Issue on channel update

- src/ducks/apps/components/ChannelModal.jsx
The modal was still open after the install
> Close correctly channel modal if this is the current channel

- package.json
- src/ducks/apps/components/ApplicationPage/Details.jsx
- test/ducks/apps/components/applicationPage/__snapshots__/details.spec.js.snap
- test/ducks/apps/components/applicationPage/details.spec.js
- test/jestLib/setup.js
- yarn.lock
Prevent channel switch display if the app is not from the registry or not installed
> Fix channel switching

- src/ducks/apps/components/InstallModal.jsx
- test/ducks/apps/components/__snapshots__/installModal.spec.js.snap
- test/ducks/apps/components/applicationRouting/__snapshots__/index.spec.js.snap
- test/ducks/apps/components/applicationRouting/index.spec.js
- test/ducks/apps/components/installModal.spec.js
* Fix the issue
* Add tests about this use case
> Correctly open install modal if manual update available

- manifest.webapp
- src/lib/getFilteredAppsFromSearch.js
- test/ducks/apps/__snapshots__/index.spec.js.snap
- test/ducks/apps/_mockApps.js
- test/ducks/apps/components/__snapshots__/appsSection.spec.js.snap
- test/ducks/apps/components/__snapshots__/discover.spec.js.snap
- test/ducks/apps/components/__snapshots__/myApplications.spec.js.snap
- test/ducks/apps/components/__snapshots__/sections.spec.js.snap
- test/ducks/apps/components/applicationRouting/__snapshots__/index.spec.js.snap
- test/ducks/apps/components/applicationRouting/__snapshots__/installRoute.spec.js.snap
- test/lib/__snapshots__/getFilteredAppsFromSearch.spec.js.snap
- test/lib/__snapshots__/helpers.spec.js.snap
- test/lib/getFilteredAppsFromSearch.spec.js
Just add the query `pendingUpdate=true` in the URL to get this filtered view
> Add a filtered view to get only pending update apps

- src/ducks/apps/components/ApplicationRouting/ChannelRoute.jsx
- src/ducks/apps/components/ApplicationRouting/InstallRoute.jsx
- src/ducks/apps/components/ChannelModal.jsx
- src/ducks/apps/components/InstallModal.jsx
- src/ducks/apps/reducers.js
- test/ducks/apps/__snapshots__/reducers.spec.js.snap
- test/ducks/apps/components/__snapshots__/channelModal.spec.js.snap
- test/ducks/apps/components/applicationRouting/__snapshots__/channelRoute.spec.js.snap
- test/ducks/apps/components/applicationRouting/__snapshots__/installRoute.spec.js.snap
- test/ducks/apps/components/channelModal.spec.js
- test/ducks/apps/components/installModal.spec.js
- test/ducks/apps/reducers.spec.js
* Fix application update in install modal
* Correctly remove the available version on update
* Some improvements and tests added
> Fix install update

- src/ducks/apps/components/PermissionsList.jsx
- src/locales/en.json
Use a generic way to handle partner external permission description
> Better partner permission text

- package.json
- src/ducks/apps/components/AppInstallation.jsx
- src/ducks/apps/components/ApplicationPage/Header.jsx
- src/ducks/apps/components/ApplicationRouting/InstallRoute.jsx
- src/ducks/apps/components/ChannelModal.jsx
- src/ducks/apps/components/Discover.jsx
- src/ducks/apps/components/InstallModal.jsx
- src/ducks/apps/components/UninstallModal.jsx
- src/ducks/apps/index.js
- src/ducks/apps/reducers.js
- src/ducks/components/App.jsx
- src/ducks/components/ApplicationPageLoading.jsx
- src/locales/en.json
- src/styles/application.css
- src/styles/install.css
- src/styles/partnership.css
- test/__mocks__/react.js
- test/ducks/apps/components/__snapshots__/channelModal.spec.js.snap
- test/ducks/apps/components/__snapshots__/installModal.spec.js.snap
- test/ducks/apps/components/applicationPage/__snapshots__/header.spec.js.snap
- test/ducks/apps/components/applicationPage/__snapshots__/index.spec.js.snap
- test/ducks/apps/components/applicationPage/header.spec.js
- test/ducks/apps/components/applicationPage/index.spec.js
- test/ducks/apps/components/applicationRouting/__snapshots__/installRoute.spec.js.snap
- test/ducks/apps/components/channelModal.spec.js
- test/ducks/apps/components/installModal.spec.js
- test/ducks/apps/reducers.spec.js
- yarn.lock
* Minor UI/text changes
* Better install/Update UI process: now we don't keep the modal opened during the installation except for the konnector since we need to redirect to the configure modal
* Update cozy-ui to get last alerter changes
> Install/Update UI process improvements

- .travis.yml
Most branches are topic branches that don't need to tested by travis until a PR is made.
> chore: :wrench: Start travis builds only for master and PRs

- package.json
- src/ducks/apps/index.js
- yarn.lock
A lot of fixes and improvements with this new version
> Use cozy-realtime v2

- src/config/apps.json
The whole onboarding is now part of the stack.
> chore: Remove the onboarding from the hidden apps

- src/targets/browser/index.ejs
- src/targets/intents/index.ejs
- Fix the glitch when the app is loading
- Do not load twice `fonts.css`
- Use the favicon helper
> Improve html

- src/targets/browser/index.ejs
- src/targets/intents/index.ejs
This reverts commit 6696b28d989c105fbf38201688812c8cfd3b5c8e.
> Revert "chore: Use the favicon from the stack"

- package.json
- src/targets/browser/index.jsx
- yarn.lock
Will be used also in the application in the future
> Add cozy-client for the Bar

- src/ducks/apps/components/AppInstallation.jsx
Was blocking the installation with an infinite loader modal
> Handle terms if permissions skipped

- src/ducks/components/Root.jsx
> Use relative path for locales in i18n

- package.json
- src/targets/services/installSuggestion.js
- yarn.lock
Use cozy-logger to log things to worker system
> Better suggestion service

- src/config/index.json
- src/ducks/apps/components/Sections.jsx
- src/ducks/components/App.jsx
- src/ducks/components/Sidebar.jsx
- src/lib/isNavigationEnabled.js
- src/styles/sections.css
- src/styles/smallAppItem.css
- test/__snapshots__/app.spec.js.snap
- test/components/__snapshots__/sidebar.spec.js.snap
- test/components/sidebar.spec.js
- test/ducks/apps/components/__snapshots__/sections.spec.js.snap
- test/ducks/apps/components/sections.spec.js
- test/lib/isNavigationEnabled.spec.js
* Hide sidebar/filter with `nav=false` as URL query
* Add configuration to display store parts or not
> Make store parts configurable + add flag to hide navigation (sidebar)

- src/config/categories.json
Wait for this PR to be merged and deployed to have all translations https://github.com/cozy/cozy-ui/pull/1004#pullrequestreview-241625457
> Add eduction category

- src/ducks/components/App.jsx
`enabledPages` may be undefined in config, so let set a default one.
> feat: Use default enabled page 📝

- src/locales/en.json
This sentence already appears in ToS which is sufficient.
> feat(locales): Remove useless sentence

- src/locales/en.json
Add apps suggestions to locales
> feat: Add apps suggestions to locales

- package.json
- src/config/permissionsIcons.json
- yarn.lock
- Apps suggestions permission is shown with the apps icon.
- Add locales
> feat: Add io.cozy.apps.suggestions

- manifest.webapp
- package.json
*Please explain what this PR does here.*
If this PR relies on changes in one of our internal libraries (cozy-client-js or cozy-ui, for example), please also do the following things:
*(If not, please remove this last section.)*
> Bump to 1.9.4

- manifest.webapp
- package.json
> chore: bump 1.9.5

- src/locales/en.json
- test/components/__snapshots__/appVote.spec.js.snap
Hi,
Upon using Cozy I noticed this piece of copy that has been bugging me a bit. Opening a PR to update two minor things I have noticed
- Changed the structure of the sentence to tone it down a bit and make it bit more idiomatic
- Update "connection" spelling to its most common form
> feat: Update "app_vote" entry for english locale

- src/targets/browser/index.jsx
- src/targets/intents/index.jsx
> feat: Register flag plugin

- manifest.webapp
- package.json
Bump version from 1.9.7 to 1.9.8
> fix: Bump version from 1.9.7 to 1.9.8

- manifest.webapp
- package.json
Bump version from 1.9.8 to 1.9.9
> Bump version from 1.9.8 to 1.9.9

- src/ducks/apps/index.js
- src/targets/browser/index.ejs
- src/targets/browser/index.jsx
- src/targets/intents/index.ejs
- src/targets/intents/index.jsx
- test/ducks/apps/index.spec.js
We decided to use data-cozy={{}} to get access to
the variables injected by the cozy-stack
> refactor: Use CozyData

- package.json
- yarn.lock
> fix: Upgrade cozy-app-publish

- manifest.webapp
chore: Bump store version to 1.9.11
Also bump the manifest
> chore: Also update the manifest

- package.json
- yarn.lock
> fix: Upgrade CC

- manifest.webapp
- package.json
*Please explain what this PR does here.*
If this PR relies on changes in one of our internal libraries (cozy-client-js or cozy-ui, for example), please also do the following things:
*(If not, please remove this last section.)*
> feat: Bump version from 1.9.11 to 1.9.12

- src/ducks/apps/components/ApplicationPage/index.jsx
- src/ducks/apps/components/ConfigureModal.jsx
- src/ducks/components/Root.jsx
- test/ducks/apps/components/applicationPage/__snapshots__/index.spec.js.snap
- test/ducks/apps/components/applicationPage/index.spec.js
> refactor: Fix Proptype issue

- manifest.webapp
- package.json
*Please explain what this PR does here.*
If this PR relies on changes in one of our internal libraries (cozy-client-js or cozy-ui, for example), please also do the following things:
*(If not, please remove this last section.)*
> feat: Bump version from 1.9.12 to 1.9.13

- package.json
- yarn.lock
I think this package has been added by mistake here https://github.com/cozy/cozy-store/pull/732/files
> fix: Remove unsued package

- src/ducks/apps/components/Sections/Sections.jsx
- src/ducks/apps/components/Sections/components/Filters.jsx
- src/ducks/apps/components/SidebarCategories.jsx
```
* Show active categories with other filters than categories
* Keep underMaintenance active between search, reloads, filter change
```
> Fix : Keep underMaintenance active between search, reloads, filter change

- src/ducks/apps/components/PermissionsList.jsx
- src/locales/en.json
- src/locales/fr.json
- test/ducks/apps/components/__snapshots__/permissionsList.spec.js.snap
```
* Rewording the consent page when installing a connector
```
> feat: Rewording the consent page when installing a connector

- src/ducks/apps/components/Discover.jsx
- src/ducks/apps/components/MyApplications.jsx
- src/ducks/apps/components/QuerystringSections.jsx
- src/ducks/apps/components/Sections/Sections.jsx
- test/ducks/apps/components/__snapshots__/discover.spec.js.snap
- test/ducks/apps/components/__snapshots__/myApplications.spec.js.snap
```
* Show maintenance filter only on Discover page
```
> Fix: show maintenance app on myapps

- manifest.webapp
- package.json
```
* Bump version from 1.9.14 to 1.9.15
```
> feat: Bump version from 1.9.14 to 1.9.15

- manifest.webapp
- package.json
```
* Bump version from 1.9.15 to 1.9.16
```
> feat: Bump version from 1.9.15 to 1.9.16

- src/ducks/components/AppRouter.jsx
- src/ducks/components/intents/IntentRedirect.jsx
```
* Make redirect route working with react-router v6
```
> fix(IntentRedirect): Convert to react-router v6 with useLocation

- .tx/config
- CONTRIBUTING.md
- README.md
```
* Migrate transifex config from v2 to v3
```
> chore: Migrate transifex config from v2 to v3

- src/locales/de.json
- src/locales/en.json
- src/locales/fr.json
- src/locales/nl_NL.json
- src/locales/pl.json
- src/styles/application.css
- test/ducks/apps/components/__snapshots__/permissionsList.spec.js.snap
```
* Update wording of konnector descrpition
* Change the display order on the Details page in Mobile mode
```
> Feat: Update wording

- manifest.webapp
- package.json
> chore: Bump from `1.9.17` to `1.9.18`

- src/ducks/apps/components/ApplicationRouting/index.jsx
- src/ducks/apps/components/Sections/Sections.jsx
- src/ducks/apps/components/Sections/index.spec.jsx
- src/ducks/search/components.jsx
- src/styles/application.css
```
* In `INSTALL` Intent, some content in ApplicationPage were not visible
```
> Fix(intent): Some content in ApplicationPage were not visible

- package.json
- src/config/categories.json
- src/ducks/components/AppVote.jsx
- src/locales/en.json
- src/locales/fr.json
- test/components/__snapshots__/appVote.spec.js.snap
- yarn.lock
```
* Change voting link so it redirects to the product board wishlist
* Add pro category for konnectors
```
**Related PRs:**
- https://github.com/cozy/cozy-ui/pull/2521
> feat: Small improvements

- src/styles/appVote.css
Decided not to update cozy-ui for this issue.
Handling it locally with already existing css classes
> fix: Reduce click area on app vote component (VO-172)

- src/ducks/components/intents/InstallAppIntent.jsx
* Removed an issue where InstallAppAttent was not executing the success callback for a webapp
* Removed redundant "already installed" error after install success
> fix: Improve installAppIntent UX (VO-414)

- package.json
- src/ducks/components/Root.jsx
- src/targets/browser/index.jsx
- src/targets/intents/index.jsx
- yarn.lock
```
*
*
* Update cozy-ui to 110.1.0 (better dark mode support)
```
> feat: Update cozy-ui to 110.1.0

- package.json
- src/config/categories.json
- src/locales/de.json
- src/locales/en.json
- src/locales/fr.json
- src/locales/nl_NL.json
- src/locales/pl.json
- yarn.lock
```
* Adds "clouds", "finance" and "tech" in known categories
* Adds new locales for each new categories
```
> [SCR-683] feat: Add new categories to the store and their locales

- .eslintrc.json
- jest.config.js
- package.json
- src/ducks/apps/components/AppInstallation.jsx
- src/ducks/apps/components/ApplicationRouting/helpers.js
- src/ducks/apps/components/ChannelModal.jsx
- src/ducks/apps/components/InstallModal.jsx
- src/ducks/apps/components/PermissionsList.jsx
- src/ducks/apps/components/UninstallModal.jsx
- src/ducks/components/App.jsx
- src/ducks/components/AppsLoading.jsx
- src/ducks/components/intents/InstallAppIntent.jsx
- src/ducks/search/utils.spec.js
- test/ducks/apps/reducers.spec.js
- tsconfig.json
- yarn.lock
This will allow to lint TS code
https://prettier.io/blog/2019/11/09/1.19.0.html
> Feat : update prettier to 1.19 and config ts lint

- package.json
- yarn.lock
```
* Update cozy-ui from 111.13.0 to 111.15.1
```
> feat: Update cozy-ui from 111.13.0 to 111.15.1

- src/config/apps.json
- src/ducks/apps/index.js
- test/ducks/apps/__snapshots__/index.spec.js.snap
```
* Hide apps by flag `apps.hidden`
*
*
```
> [PRD-538] Hide apps by flag
